parameters:
- name: RunOnnxRuntimeTests
  displayName: Run Tests?
  type: boolean
  default: true

- name: DoCompliance
  displayName: Run Compliance Tasks?
  type: boolean
  default: true

- name: DoEsrp
  displayName: Run code sign tasks? Must be true if you are doing an Onnx Runtime release.
  type: boolean
  default: false

- name: IsReleaseBuild
  displayName: Is a release build? Set it to true if you are doing an Onnx Runtime release.
  type: boolean
  default: false

- name: AdditionalBuildFlags
  displayName: Additional build flags for build.py
  type: string
  default: ''

- name: AdditionalWinBuildFlags
  displayName: Additional build flags that just for Windows Builds
  type: string
  default: ''

- name: OrtNugetPackageId
  displayName: Package name for nuget
  type: string
  default: 'Microsoft.ML.OnnxRuntime'

- name: BuildVariant
  type: string
  default: 'default'

- name: SpecificArtifact
  displayName: Use Specific Artifact
  type: boolean
  default: false

- name: BuildId
  displayName: Specific Artifact's BuildId
  type: string
  default: '0'

stages:

- template: win-ci.yml
  parameters:
    DoCompliance: ${{ parameters.DoCompliance }}
    DoEsrp: ${{ parameters.DoEsrp }}
    stage_name_suffix: CPU_x64_${{ parameters.BuildVariant }}
    buildArch: x64
    msbuildPlatform: x64
    packageName: x64
    buildparameter: --build_java --build_nodejs ${{ parameters.AdditionalBuildFlags }}  ${{ parameters.AdditionalWinBuildFlags}}
    runTests: ${{ parameters.RunOnnxRuntimeTests }}
    buildJava: true
    buildNodejs: true

- stage: Nodejs_Packaging_CPU
  dependsOn:
  - Linux_C_API_Packaging_GPU_TensorRT_x64
  - Windows_CI_GPU_DML_Dev
  - Windows_Packaging_CPU_x64_${{ parameters.BuildVariant }}
#  - Windows_Packaging_CPU_arm64_${{ parameters.BuildVariant }}
  condition: succeeded()
  jobs:
  - job:
    workspace:
      clean: all
    pool: 'onnxruntime-Win-CPU-2022'
    variables:
      ${{ if eq(parameters.IsReleaseBuild, true) }}:
        NpmPackagingMode: 'release'
      ${{ if not(eq(parameters.IsReleaseBuild, true)) }}:
        NpmPackagingMode: 'dev'
      breakCodesignValidationInjection: ${{ parameters.DoEsrp }}

    steps:
    - checkout: self
      submodules: true
    - script: |
       echo.>>.gitattributes
       echo /js/** text=auto eol=lf>>.gitattributes
       rd /s /q js
       git checkout -- js/**
       git checkout -- .gitattributes
      workingDirectory: '$(Build.SourcesDirectory)'
      displayName: 'Testing: force EOL to lf on windows for /js/**'
# This artifact is from Windows_CI_GPU_DML_Dev
    - task: DownloadPipelineArtifact@0
      displayName: 'Download Pipeline Artifact - Nodejs (Win x64)'
      inputs:
        artifactName: 'drop-onnxruntime-nodejs-win-x64-dml'
        targetPath: '$(Build.BinariesDirectory)/nodejs-artifacts/win32/x64/'

#    - task: DownloadPipelineArtifact@0
#      displayName: 'Download Pipeline Artifact - Nodejs (Win ARM64)'
#      inputs:
#        artifactName: 'drop-onnxruntime-nodejs-win-arm64-dml'
#        targetPath: '$(Build.BinariesDirectory)/nodejs-artifacts/win32/arm64/'
# Linux - Nuget
    - task: DownloadPipelineArtifact@0
      displayName: 'Download Pipeline Artifact - NuGet (Linux x64)'
      inputs:
        artifactName: 'onnxruntime-linux-x64-tensorrt'
        targetPath: '$(Build.BinariesDirectory)/nuget-artifact'

#    - task: DownloadPipelineArtifact@0
#      displayName: 'Download Pipeline Artifact - NuGet (Linux aarch64)'
#      inputs:
#        artifactName: 'onnxruntime-linux-aarch64'
#        targetPath: '$(Build.BinariesDirectory)/nuget-artifact'

# Linux - Nodejs
    - task: DownloadPipelineArtifact@0
      displayName: 'Download Pipeline Artifact - Nodejs (Linux x64)'
      inputs:
        artifactName: 'drop-onnxruntime-nodejs-linux-x64-tensorrt'
        targetPath: '$(Build.BinariesDirectory)/nodejs-artifacts/linux/x64/'
    - script: |
       dir
      workingDirectory: '$(Build.BinariesDirectory)/nodejs-artifacts/win32/x64/'
      displayName: 'List Nodejs artifacts from $(Build.BinariesDirectory)/nodejs-artifacts/win32/x64/'

#    - task: DownloadPipelineArtifact@0
#      displayName: 'Download Pipeline Artifact - Nodejs (Linux aarch64)'
#      inputs:
#        artifactName: 'drop-onnxruntime-nodejs-linux-aarch64'
#        targetPath: '$(Build.BinariesDirectory)/nodejs-artifacts/linux/arm64/'


    - task: DownloadPipelineArtifact@0
      displayName: 'Download Pipeline Artifact - NuGet'
      inputs:
        artifactName: 'drop-extra'
        targetPath: '$(Build.BinariesDirectory)/extra-artifact'

    - task: PowerShell@2
      displayName: 'PowerShell Script'
      inputs:
        targetType: filePath
        filePath: $(Build.SourcesDirectory)\tools\ci_build\github\windows\extract_nuget_files.ps1
    - script: |
       dir
      workingDirectory: '$(Build.BinariesDirectory)/nuget-artifact'
      displayName: 'List artifacts'

    - script: |
       npm ci
      workingDirectory: '$(Build.SourcesDirectory)/js'
      displayName: 'Install NPM packages /js'
    - script: |
       npm ci
      workingDirectory: '$(Build.SourcesDirectory)/js/common'
      displayName: 'Install NPM packages /js/common'
    - script: |
       npm ci
      workingDirectory: '$(Build.SourcesDirectory)/js/node'
      displayName: 'Install NPM packages /js/node'

    # Node.js binding win32/x64
    - task: CopyFiles@2
      displayName: 'Copy nuget binaries to: $(Build.SourcesDirectory)\js\node\bin\napi-v3\win32\x64\'
      inputs:
        SourceFolder: '$(Build.BinariesDirectory)\nodejs-artifacts\win32\x64'
        Contents: '*.dll'
        TargetFolder: '$(Build.SourcesDirectory)\js\node\bin\napi-v3\win32\x64'
    - task: CopyFiles@2
      displayName: 'Copy nodejs binaries to: $(Build.SourcesDirectory)\js\node\bin\napi-v3\win32\x64\'
      inputs:
        SourceFolder: '$(Build.BinariesDirectory)\nodejs-artifacts\win32\x64'
        Contents: '*.node'
        TargetFolder: '$(Build.SourcesDirectory)\js\node\bin\napi-v3\win32\x64'

#    # Node.js binding win32/arm64
#    - task: CopyFiles@2
#      displayName: 'Copy nuget binaries to: $(Build.SourcesDirectory)\js\node\bin\napi-v3\win32\arm64\'
#      inputs:
#        SourceFolder: '$(Build.BinariesDirectory)\RelWithDebInfo\RelWithDebInfo\nuget-artifacts\onnxruntime-win-arm64\lib'
#        Contents: '*.dll'
#        TargetFolder: '$(Build.SourcesDirectory)\js\node\bin\napi-v3\win32\arm64'
#    - task: CopyFiles@2
#      displayName: 'Copy nodejs binaries to: $(Build.SourcesDirectory)\js\node\bin\napi-v3\win32\arm64\'
#      inputs:
#        SourceFolder: '$(Build.BinariesDirectory)\nodejs-artifacts\win32\arm64'
#        Contents: '*.node'
#        TargetFolder: '$(Build.SourcesDirectory)\js\node\bin\napi-v3\win32\arm64'

    # Node.js binding linux/x64

    - task: CopyFiles@2
      displayName: 'Copy nuget binaries to: $(Build.SourcesDirectory)\js\node\bin\napi-v3\linux\x64\'
      inputs:
        SourceFolder: '$(Build.BinariesDirectory)\RelWithDebInfo\RelWithDebInfo\nuget-artifacts\onnxruntime-linux-x64-tensorrt\lib'
        Contents: 'libonnxruntime.so.*'
        TargetFolder: '$(Build.SourcesDirectory)\js\node\bin\napi-v3\linux\x64'
    - task: CopyFiles@2
      displayName: 'Copy nodejs binaries to: $(Build.SourcesDirectory)\js\node\bin\napi-v3\linux\x64\'
      inputs:
        SourceFolder: '$(Build.BinariesDirectory)\nodejs-artifacts\linux\x64'
        Contents: '*.node'
        TargetFolder: '$(Build.SourcesDirectory)\js\node\bin\napi-v3\linux\x64'

#    # Node.js binding linux/arm64
#    - task: CopyFiles@2
#      displayName: 'Copy nuget binaries to: $(Build.SourcesDirectory)\js\node\bin\napi-v3\linux\arm64\'
#      inputs:
#        SourceFolder: '$(Build.BinariesDirectory)\RelWithDebInfo\RelWithDebInfo\nuget-artifacts\onnxruntime-linux-aarch64\lib'
#        Contents: 'libonnxruntime.so.*'
#        TargetFolder: '$(Build.SourcesDirectory)\js\node\bin\napi-v3\linux\arm64'
#    - task: CopyFiles@2
#      displayName: 'Copy nodejs binaries to: $(Build.SourcesDirectory)\js\node\bin\napi-v3\linux\arm64\'
#      inputs:
#        SourceFolder: '$(Build.BinariesDirectory)\nodejs-artifacts\linux\arm64'
#        Contents: '*.node'
#        TargetFolder: '$(Build.SourcesDirectory)\js\node\bin\napi-v3\linux\arm64'

#    # Node.js binding darwin/x64
#    - task: CopyFiles@2
#      displayName: 'Copy nuget binaries to: $(Build.SourcesDirectory)\js\node\bin\napi-v3\darwin\x64\'
#      inputs:
#        SourceFolder: '$(Build.BinariesDirectory)\RelWithDebInfo\RelWithDebInfo\nuget-artifacts\onnxruntime-osx-x86_64\lib'
#        Contents: 'libonnxruntime.*.dylib'
#        TargetFolder: '$(Build.SourcesDirectory)\js\node\bin\napi-v3\darwin\x64'
#    - task: CopyFiles@2
#      displayName: 'Copy nodejs binaries to: $(Build.SourcesDirectory)\js\node\bin\napi-v3\darwin\x64\'
#      inputs:
#        SourceFolder: '$(Build.BinariesDirectory)\nodejs-artifacts\darwin\x64'
#        Contents: '*.node'
#        TargetFolder: '$(Build.SourcesDirectory)\js\node\bin\napi-v3\darwin\x64'
#
#    # Node.js binding darwin/arm64
#    - task: CopyFiles@2
#      displayName: 'Copy nuget binaries to: $(Build.SourcesDirectory)\js\node\bin\napi-v3\darwin\arm64\'
#      inputs:
#        SourceFolder: '$(Build.BinariesDirectory)\RelWithDebInfo\RelWithDebInfo\nuget-artifacts\onnxruntime-osx-arm64\lib'
#        Contents: 'libonnxruntime.*.dylib'
#        TargetFolder: '$(Build.SourcesDirectory)\js\node\bin\napi-v3\darwin\arm64'
#    - task: CopyFiles@2
#      displayName: 'Copy nodejs binaries to: $(Build.SourcesDirectory)\js\node\bin\napi-v3\darwin\arm64\'
#      inputs:
#        SourceFolder: '$(Build.BinariesDirectory)\nodejs-artifacts\darwin\arm64'
#        Contents: '*.node'
#        TargetFolder: '$(Build.SourcesDirectory)\js\node\bin\napi-v3\darwin\arm64'

    - task: PowerShell@2
      inputs:
        filePath: '$(Build.SourcesDirectory)\tools\ci_build\github\js\pack-npm-packages.ps1'
        arguments: '$(NpmPackagingMode) $(Build.SourcesDirectory) node'
        workingDirectory: $(Build.BinariesDirectory)
        errorActionPreference: stop
      displayName: 'Pack NPM packages'

    - task: CopyFiles@2
      displayName: 'Copy onnxruntime-common package to staging directory'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/js/common/'
        Contents: 'onnxruntime-common-*.tgz'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: CopyFiles@2
      displayName: 'Copy onnxruntime-node package to staging directory'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/js/node/'
        Contents: 'onnxruntime-node-*.tgz'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishPipelineArtifact@0
      displayName: 'Publish NPM packages files'
      inputs:
        artifactName: 'NPM_packages'
        targetPath: '$(Build.ArtifactStagingDirectory)'

    - template: component-governance-component-detection-steps.yml
      parameters :
        condition : 'succeeded'

    - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
      displayName: 'Clean Agent Directories'
      condition: always()

#- template: ../nuget/templates/test_win.yml
#  parameters:
#    AgentPool : 'onnxruntime-Win-CPU-2022'
#    Skipx86Tests : false
#    NugetPackageName : 'Microsoft.ML.OnnxRuntime'
#    ArtifactSuffix: 'CPU'
#    SpecificArtifact: ${{ parameters.SpecificArtifact }}
#    BuildId: ${{ parameters.BuildId }}
#
#- template: ../nuget/templates/test_linux.yml
#  parameters:
#    AgentPool : onnxruntime-Ubuntu2004-AMD-CPU
#    NugetPackageName : 'Microsoft.ML.OnnxRuntime'
#    ArtifactSuffix: 'CPU'
#    SpecificArtifact: ${{ parameters.SpecificArtifact }}
#    BuildId: ${{ parameters.BuildId }}

#- template: ../nuget/templates/test_macos.yml
#  parameters:
#    AgentPool : macOS-13
#    ArtifactSuffix: 'CPU'

#- template: ../nodejs/templates/test_win.yml
#  parameters:
#    AgentPool : 'onnxruntime-Win-CPU-2022'
#    StageSuffix : 'Win_CPU_x64'
#
#- template: ../nodejs/templates/test_linux.yml
#  parameters:
#    AgentPool : 'Azure-Pipelines-EO-Ubuntu-2004-aiinfra'
#    StageSuffix : 'Linux_CPU_x64'

#- template: ../nodejs/templates/test_macos.yml
#  parameters:
#    StageSuffix : 'macOS_CPU_x64'

#- template: final-jar-testing.yml
#  parameters:
#    OS: Windows
#    BuildId: ${{ parameters.BuildId }}
#    SpecificArtifact: ${{ parameters.SpecificArtifact }}
#    PoolName: 'onnxruntime-Win-CPU-2022'
#
#- template: final-jar-testing.yml
#  parameters:
#    OS: Linux
#    BuildId: ${{ parameters.BuildId }}
#    SpecificArtifact: ${{ parameters.SpecificArtifact }}
#    PoolName: 'onnxruntime-Ubuntu2004-AMD-CPU'
#
#- template: final-jar-testing.yml
#  parameters:
#    OS: MacOS
#    BuildId: ${{ parameters.BuildId }}
#    SpecificArtifact: ${{ parameters.SpecificArtifact }}
#    PoolName: 'macOS-13'
