steps:
  - task: UseNode@1
    displayName: 'Install Node.js'
    inputs:
      versionSpec: 16.x

  - task: Cache@2
    inputs:
      key: onnxtestdata | $(Build.SourcesDirectory)/js/scripts/prepare-onnx-node-tests.ts
      restoreKeys: |
        onnxtestdata | $(Build.SourcesDirectory)/js/scripts/prepare-onnx-node-tests.ts
      path: $(Agent.TempDirectory)/data/onnx/
      cacheHitVar: CACHE_RESTORED
    displayName: 'Cache ONNX node test data'

  - script: |
     set -ex
     if [[ ! -e "$(Agent.TempDirectory)/data/onnx/node/__generated_onnx_node_tests" ]]; then
        rm -rf $(Agent.TempDirectory)/data/onnx
        cd $(Build.SourcesDirectory)/js/
        npm install
        npm run prepare-onnx-node-tests
        find . $(Agent.TempDirectory)/data/onnx
     fi
    workingDirectory: '$(Build.SourcesDirectory)/js/web'
    displayName: 'Download ONNX node test data'
