- task: Cache@2
  inputs:
    key: onnxtestdata | $(Build.SourcesDirectory)/js/scripts/prepare-onnx-node-tests.ts
    restoreKeys: |
      onnxtestdata | $(Build.SourcesDirectory)/js/scripts/prepare-onnx-node-tests.ts
    path: $(Agent.TempDirectory)/data/onnx
    cacheHitVar: CACHE_RESTORED
  displayName: 'Cache ONNX node test data'
