parameters:
- name: CommitOverride
  type: boolean
  default: false

- name: BuildConfig
  type: string
  default: 'Debug'

- name: ExtraBuildArgs
  type: string
  default: ''

- name: PoolName
  type: string
  default: 'onnxruntime-Ubuntu2004-AMD-CPU'

- name: SkipPublish
  type: boolean
  default: false

- name: TimeoutInMinutes
  default: 180

- name: BuildJsep
  type: boolean
  default: false

# In fact, it's only used on Linux for compiler cache.
- name: BuildStaticLib
  type: boolean
  default: false

- name: BuildTraining
  type: boolean
  default: true

- name: WithCache
  type: boolean
  default: false

jobs:
- job: build_WASM
  pool:
    name: ${{ parameters.PoolName }}
  variables:
    EnvSetupScript: setup_env.bat
    buildArch: x64
    CommonBuildArgs: '--parallel --config ${{ parameters.BuildConfig }} --skip_submodule_sync --build_wasm --use_xnnpack ${{ parameters.ExtraBuildArgs }}'
    runCodesignValidationInjection: false
    TODAY: $[format('{0:dd}{0:MM}{0:yyyy}', pipeline.startTime)]
    ORT_CACHE_DIR: $(Agent.TempDirectory)/ort_ccache
  timeoutInMinutes: ${{ parameters.TimeoutInMinutes }}
  workspace:
    clean: all
  steps:
  - task: mspremier.PostBuildCleanup.PostBuildCleanup-task.PostBuildCleanup@3
    displayName: 'Clean Agent Directories'
    condition: always()
  - checkout: self
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
      architecture: $(buildArch)
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
  - template: download-deps.yml

  - task: PythonScript@0
    displayName: 'Update deps.txt'
    inputs:
      scriptPath: $(Build.SourcesDirectory)/tools/ci_build/replace_urls_in_deps.py
      arguments: --new_dir $(Build.BinariesDirectory)/deps
      workingDirectory: $(Build.BinariesDirectory)

  - script: |
      set -ex
      cd '$(Build.SourcesDirectory)/cmake/external/emsdk'
      ./emsdk install 3.1.44 ccache-git-emscripten-64bit
      ./emsdk activate 3.1.44 ccache-git-emscripten-64bit
    displayName: 'emsdk install and activate ccache for emscripten'
    condition: eq('${{ parameters.WithCache }}', 'true')

  - template: build-linux-wasm-step.yml
    parameters:
      Today: $(Today)
      ${{ if eq(parameters.BuildStaticLib, true)}}:
        AdditionalKey: wasm_threads | ${{ parameters.BuildConfig }} | static
      ${{ else }}:
        AdditionalKey: wasm_threads | ${{ parameters.BuildConfig }}
      CacheDir: $(ORT_CACHE_DIR)/wasm_threads
      Arguments: '$(CommonBuildArgs) --build_dir $(Build.BinariesDirectory)/wasm_threads --enable_wasm_threads --wasm_run_tests_in_browser --target onnxruntime_test_all'
      DisplayName: 'Build and test (browser) (threads)'
      WithCache: ${{ parameters.WithCache }}

  - template: build-linux-wasm-step.yml
    parameters:
      Today: $(Today)
      ${{ if eq(parameters.BuildStaticLib, true)}}:
        AdditionalKey: wasm_simd_threads | ${{ parameters.BuildConfig }} | static
      ${{ else }}:
        AdditionalKey: wasm_simd_threads | ${{ parameters.BuildConfig }}
      CacheDir: $(ORT_CACHE_DIR)/wasm_simd_threads
      Arguments: '$(CommonBuildArgs) --build_dir $(Build.BinariesDirectory)/wasm_simd_threads --enable_wasm_simd --enable_wasm_threads --wasm_run_tests_in_browser --target onnxruntime_test_all'
      DisplayName: 'Build and test (browser) (simd + threads)'
      WithCache: ${{ parameters.WithCache }}

  - task: PublishTestResults@2
    displayName: 'Publish unit test results'
    inputs:
      testResultsFiles: '**/*.results.xml'
      searchFolder: '$(Build.BinariesDirectory)'
      testRunTitle: 'Unit Test Run'
    condition: and(succeededOrFailed(), eq('${{ parameters.BuildConfig }}', 'Debug'))
  - template: component-governance-component-detection-steps.yml
    parameters :
      condition : 'succeeded'
