parameters:
- name: msbuildPlatform
  type: string
- name: java_artifact_id
  type: string
- name: buildOnly
  type: boolean
steps:
- task: CmdLine@2
  displayName: 'Gradle cmakeBuild'
  inputs:
    script: |
      @echo on
      call gradlew.bat cmakeBuild -DcmakeBuildDir=$(Build.BinariesDirectory)\RelWithDebInfo
    workingDirectory: $(Build.SourcesDirectory)\java
    failOnStderr: true
  condition: eq(${{ parameters.buildOnly }}, true)

- task: CmdLine@2
  displayName: 'Gradle cmakeCheck'
  inputs:
    script: |
      @echo on
      call gradlew.bat cmakeCheck -DcmakeBuildDir=$(Build.BinariesDirectory)\RelWithDebInfo
    workingDirectory: $(Build.SourcesDirectory)\java
    failOnStderr: true
  condition: ne(${{ parameters.buildOnly }}, true)

- task: CmdLine@2
  displayName: 'Update onnxruntime jar with pdb files and other files'
  inputs:
    script: |
      set artifact_id=${{ parameters.java_artifact_id }}
      set JAR_FOLDER=$(Build.BinariesDirectory)\onnxruntime-java-win-${{ parameters.msbuildPlatform }}
      set STAGE_FOLDER=%JAR_FOLDER%\stage
      set NATIVE_FOLDER=%STAGE_FOLDER%\ai\onnxruntime\native\win-x64
      jar xf %JAR_FOLDER%\onnxruntime-$(OnnxRuntimeVersion).jar META-INF\maven\com.microsoft.onnxruntime\%artifact_id%\pom.xml
      move META-INF\maven\com.microsoft.onnxruntime\%artifact_id%\pom.xml %JAR_FOLDER%\onnxruntime-$(OnnxRuntimeVersion).pom
      rd /s /q META-INF
      dir/s $(Build.BinariesDirectory)\RelWithDebInfo\ 
      copy $(Build.BinariesDirectory)\RelWithDebInfo\java\build\libs\*.jar %JAR_FOLDER%
      mkdir %NATIVE_FOLDER%
      copy .\RelWithDebInfo\onnxruntime.pdb %NATIVE_FOLDER%
      copy .\RelWithDebInfo\onnxruntime4j_jni.pdb %NATIVE_FOLDER%
      copy $(Build.SourcesDirectory)\docs\Privacy.md %STAGE_FOLDER%\Privacy.md
      copy $(Build.SourcesDirectory)\ThirdPartyNotices.txt %STAGE_FOLDER%\ThirdPartyNotices.txt
      @echo $(OnnxRuntimeGitCommitHash) > %STAGE_FOLDER%\GIT_COMMIT_ID
      jar uf %JAR_FOLDER%\onnxruntime-$(OnnxRuntimeVersion).jar %NATIVE_FOLDER%\onnxruntime.pdb
      jar uf %JAR_FOLDER%\onnxruntime-$(OnnxRuntimeVersion).jar %NATIVE_FOLDER%\onnxruntime4j_jni.pdb
      jar uf %JAR_FOLDER%\onnxruntime-$(OnnxRuntimeVersion).jar Privacy.md ThirdPartyNotices.txt GIT_COMMIT_ID
      jar cvf %JAR_FOLDER%\testing.jar $(Build.SourcesDirectory)\java\build\classes\java\test
      jar uvf %JAR_FOLDER%\testing.jar $(Build.SourcesDirectory)\java\build\resources\test
      rd /s /q %STAGE_FOLDER%
      dir /s /b %JAR_FOLDER%
