# runs the specified steps while logged in to the container registry

parameters:
- name: Steps
  type: stepList
- name: ContainerRegistry
  type: string

steps:
- script: |
    set -x
    az login --identity --username 63b63039-6328-442f-954b-5a64d124e5b4
    az acr login -n onnxruntimebuildcache
    az acr login -n onnxruntimeregistry    

- ${{ parameters.Steps }}


- script: |
    docker logout onnxruntimebuildcache
    docker logout onnxruntimeregistry