##### start trigger Don't edit it manually, Please do edit set-trigger-rules.py ####
trigger:
  branches:
    include:
    - main
    - rel-*
  paths:
    exclude:
    - docs/**
    - README.md
    - CONTRIBUTING.md
    - BUILD.md
    - 'js/web'
    - 'js/common/lib'
    - 'onnxruntime/core/providers/js'
    - 'onnxruntime/wasm/js_internal_api.js'
pr:
  branches:
    include:
    - main
    - rel-*
  paths:
    exclude:
    - docs/**
    - README.md
    - CONTRIBUTING.md
    - BUILD.md
    - 'js/web'
    - 'js/common/lib'
    - 'onnxruntime/core/providers/js'
    - 'onnxruntime/wasm/js_internal_api.js'
#### end trigger ####

stages:
- template: templates/mac-cpu-packaging-pipeline.yml
  parameters:
    AllowReleasedOpsetOnly: 0
    BuildForAllArchs: false
    AdditionalBuildFlags: --enable_training --build_objc
    WithCache: true
