##### start trigger Don't edit it manually, Please do edit set-trigger-rules.py ####
trigger:
  branches:
    include:
    - main
    - rel-*
  paths:
    exclude:
    - docs/**
    - README.md
    - CONTRIBUTING.md
    - BUILD.md
    - 'js/web'
    - 'onnxruntime/core/providers/js'
pr:
  branches:
    include:
    - main
    - rel-*
  paths:
    exclude:
    - docs/**
    - README.md
    - CONTRIBUTING.md
    - BUILD.md
    - 'js/web'
    - 'onnxruntime/core/providers/js'
#### end trigger ####

parameters:

- name: QnnSdk
  displayName: QNN SDK version
  type: string
  default: 2.21.0.240401

- name: DoCompliance
  displayName: Run Compliance Tasks?
  type: boolean
  default: false

jobs:
- job: 'build'
  pool: 'Onnxruntime-QNNEP-Windows-2022-CPU'
  variables:
    MsbuildArguments: '-detailedsummary -maxcpucount -consoleloggerparameters:PerformanceSummary'
    OnnxRuntimeBuildDirectory: '$(Build.BinariesDirectory)'
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    buildArch: x64
    setVcvars: true
    BuildConfig: 'RelWithDebInfo'
    ALLOW_RELEASED_ONNX_OPSET_ONLY: '1'
    TODAY: $[format('{0:dd}{0:MM}{0:yyyy}', pipeline.startTime)]
  timeoutInMinutes: 120
  workspace:
    clean: all
  steps:

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
      architecture: $(buildArch)

  - template: templates/jobs/download_win_qnn_sdk.yml
    parameters:
      QnnSDKVersion: ${{ parameters.QnnSdk }}

  - template: templates/jobs/win-ci-build-steps.yml
    parameters:
      WithCache: True
      Today: $(TODAY)
      AdditionalKey: "win-qnn | $(BuildConfig)"
      BuildPyArguments: '--config $(BuildConfig) --build_dir $(Build.BinariesDirectory) --update --cmake_generator "Visual Studio 17 2022" --use_qnn --qnn_home $(QnnSDKRootDir) --parallel --use_binskim_compliant_compile_flags'
      MsbuildArguments: $(MsbuildArguments)
      BuildArch: $(buildArch)
      Platform: 'x64'
      BuildConfig: $(BuildConfig)

  - ${{ if eq(parameters['DoCompliance'], 'true') }}:
    - task: CredScan@3
      displayName: 'Run CredScan'
      inputs:
        debugMode: false
      continueOnError: true

    - task: BinSkim@4
      displayName: 'Run BinSkim'
      inputs:
        AnalyzeTargetGlob: '$(Build.SourcesDirectory)\$(BuildConfig)\$(BuildConfig)\**\*.dll'
      continueOnError: true

    - task: PostAnalysis@2
      inputs:
        GdnBreakAllTools: false
        GdnBreakGdnToolBinSkim: true
        GdnBreakPolicy: M365
        GdnBreakPolicyMinSev: Error

  - powershell: |
     python $(Build.SourcesDirectory)\tools\ci_build\build.py --config $(BuildConfig) --build_dir $(Build.BinariesDirectory) --skip_submodule_sync --test --cmake_generator "Visual Studio 17 2022" --enable_onnx_tests
    workingDirectory: '$(Build.BinariesDirectory)\$(BuildConfig)\$(BuildConfig)'
    displayName: 'Run unit tests'

  - script: |
      .\$(BuildConfig)\onnx_test_runner -j 1 -v -e qnn -i "backend_path|$(QnnSDKRootDir)\lib\x86_64-windows-msvc\QnnCpu.dll" $(Build.SourcesDirectory)\cmake\external\onnx\onnx\backend\test\data\node
    workingDirectory: '$(Build.BinariesDirectory)\$(BuildConfig)'
    displayName: 'Run ONNX Tests'

  - script: |
      .\$(BuildConfig)\onnx_test_runner -j 1 -v -e qnn -i "backend_path|$(QnnSDKRootDir)\lib\x86_64-windows-msvc\QnnCpu.dll" C:\data\float32_models
    workingDirectory: '$(Build.BinariesDirectory)\$(BuildConfig)'
    displayName: 'Run float32 model tests'
