parameters:
  - name: DownloadCUDA
    type: boolean
    default: false
  - name: DownloadTRT
    type: boolean
    default: false
  - name: CUDA_Version
    type: string
    default: '12.2'

steps:

  - ${{ if eq(parameters.DownloadCUDA, true) }}:
    - powershell: |
        azcopy.exe cp --recursive https://lotusscus.blob.core.windows.net/models/cuda_sdk/v${{ parameters.CUDA_Version }} $(Agent.TempDirectory)
      displayName: 'Download CUDA SDK v${{ parameters.CUDA_Version }}'
    - powershell: |
        Write-Host "##vso[task.prependpath]$(Agent.TempDirectory)\v${{ parameters.CUDA_Version }}\bin;$(Agent.TempDirectory)\v${{ parameters.CUDA_Version }}\extras\CUPTI\lib64"
      displayName: 'Append CUDA SDK Directory to PATH'
    - task: CmdLine@2
      inputs:
        script: |
          echo %PATH%
      displayName: 'Print PATH'

  - ${{ if eq(parameters.DownloadTRT, true) }}:
    - ${{ if eq(parameters.CUDA_Version, '11.8') }}:
      - powershell: |
          azcopy.exe cp --recursive https://lotusscus.blob.core.windows.net/models/local/TensorRT-8.6.1.6.Windows10.x86_64.cuda-11.8 $(Agent.TempDirectory)
        displayName: 'Download TensorRT-8.6.1.6.Windows10.x86_64.cuda-11.8'
      - powershell: |
          Write-Host "##vso[task.prependpath]$(Agent.TempDirectory)\TensorRT-8.6.1.6.Windows10.x86_64.cuda-11.8\lib"
        displayName: 'Append CUDA SDK Directory to PATH'

    - ${{ if eq(parameters.CUDA_Version, '12.2') }}:
      - powershell: |
          azcopy.exe cp --recursive https://lotusscus.blob.core.windows.net/models/local/TensorRT-8.6.1.6.Windows10.x86_64.cuda-12.0 $(Agent.TempDirectory)
        displayName: 'Download TensorRT-8.6.1.6.Windows10.x86_64.cuda-12.0'
      - powershell: |
          Write-Host "##vso[task.prependpath]$(Agent.TempDirectory)\TensorRT-8.6.1.6.Windows10.x86_64.cuda-12.0\lib"
        displayName: 'Append CUDA SDK Directory to PATH'

    - task: CmdLine@2
      inputs:
        script: |
          echo %PATH%
      displayName: 'Print PATH'