name: Windows_CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - rel-*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  AZCOPY_AUTO_LOGIN_TYPE: MSI
  AZCOPY_MSI_CLIENT_ID: 63b63039-6328-442f-954b-5a64d124e5b4

jobs:
  Windows-CUDA-12:
    runs-on: ["self-hosted", "1ES.Pool=onnxruntime-github-Win2022-GPU-A10"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: [ 'java', 'javascript', 'python', 'cpp' ]
          queries: security-extended,security-and-quality
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'
          architecture: 'x64'

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'

      - name: Download cuda
        run: azcopy.exe cp --recursive "https://lotusscus.blob.core.windows.net/models/cuda_sdk/v12.2" cuda_sdk

      - name: Test GPU
        run: nvidia-smi

      - name: Build code
        run: python tools\ci_build\build.py --enable_training --build_java --config Debug --build_dir ${{ runner.temp }} --skip_submodule_sync --build_csharp --parallel --cmake_generator "Visual Studio 17 2022" --build_shared_lib --enable_pybind --use_cuda --cuda_home=${{ github.workspace }}\cuda_sdk\v12.2 --enable_cuda_profiling  --cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=86

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3